[pytest]

pythonpath = .
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*

# Pytest Options
addopts =
    --alluredir=reports/allure-results
    -v
    --tb=short
    --strict-markers

# Custom Markers
markers =
    uiandapi: marks tests that involve both UI and API interactions
    empty: marks tests for empty title validation
    ui: marks UI-only tests
    api: marks API-only tests
    test : mark it as test
    
# Logging
